language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
# command to install dependencies
install:
    - "pip install . --use-mirrors"
    - "pip install beautifulsoup4 nose coverage python-coveralls"
# command to run tests
script:
    - nosetests --with-coverage --cover-package=yota
after_success:
    - coveralls
